### Installation

db: MySQL                   # database engine to use (in db/)
auth: Alibaba               # authentication engine to use (in auth/)

database:
  host: localhost           # hostname
  database: mydatabase      # database name
  username: dbuser          # database username
  password: dbpass          # database user's password

title: Site Title           # site title
app_url: &SITEROOT http://path/to/unbindery
sys_path: /filesystem/path/to/unbindery
admin_email: administrator@email.com        # site admin's email


### Configuration

language: en                # default language
email_subject: "[unbindery]"  # prepended to notification emails
theme_cached: false
theme: core                 # if you add a new system-wide theme, change this
external_login: false       # whether to call Auth::redirectToLogin on index page
allow_signup: true          # whether to show link to sign up
download_template: "<item item-title='{{ item.title }}' item-id='{{ item.id }}' item-type='{{ item.type }}' proofers='{{ proofers }}' reviewers='{{ reviewers }}'>{{ transcript }}</item>\n\n"  # default download template

alibaba:
  app_name: unbindery       # for Alibaba session variable
  users_table: users        # which table the user info is stored in
  username_field: username
  password_field: password
  hash_function: md5        # or sha1 or md5sha1 or sha1md5
  login_page_url: *SITEROOT

system_guidelines: |
    <i>Questions? Email your administrator (your@email.com)</i>
    <h3>General</h3>
    <p>Fix typos.</p>

private_key: 'hash together a private key and put it here'

devkeys:
  unbindery: 'hash together a dev key and put it here'

google_analytics: UA-YOUR-GA-CODE

scoring:
  proof: 5                              # how many points proofing an item is worth
  review: 5                             # how many points reviewing an item is worth

editors:
  page:
    css: # [custompage.css]             # array of CSS to include for this editor type
  audio:
    css: [me/mediaelementplayer.min.css]
    js: [me/mediaelement-and-player.min.js]
# xml:
#   css: # [xml.css]                    # custom editor type

uploaders:
  Page:
    extensions: [ jpg, jpeg, png, gif ]
  Audio:
    extensions: [ mp3 ]
    ffmpeg: /usr/local/bin/ffmpeg
    chunksize: 60                       # sixty seconds
    chunkoverlap: 2                     # two seconds

notifications:
  user_new: [ @admin ]
  user_save_transcript_draft: [ @user ]
  user_save_transcript_completed: [ @user ]
  user_save_transcript_reviewed: [ @user ]
  admin_save_transcript_draft: [ @projectadmin ]
  admin_save_transcript_completed: [ @projectadmin ]
  admin_save_transcript_reviewed: [ @projectadmin ]
