### Installation

db: MySQL                   # database engine to use (in db/)
auth: Alibaba               # authentication engine to use (in auth/)

database:
  host: localhost           # hostname
  database: mydatabase      # database name
  username: dbuser          # database username
  password: dbpass          # database user's password

title: Site Title           # site title
app_url: &SITEROOT http://path/to/unbindery
sys_path: /filesystem/path/to/unbindery
admin_email: administrator@email.com        # site admin's email


### Configuration

language: en                # default language
email_subject: "[unbindery]"  # prepended to notification emails
theme_cached: false
theme: core                 # if you add a new system-wide theme, change this
external_login: false       # whether to call Auth::redirectToLogin on index page
allow_signup: true          # whether to show link to sign up
delimiter: "\n#-#-#\n"      # the delimiter used when concatenating transcripts

alibaba:
  app_name: unbindery       # for Alibaba session variable
  users_table: users        # which table the user info is stored in
  username_field: username
  password_field: password
  hash_function: md5        # or sha1 or md5sha1 or sha1md5
  login_page_url: *SITEROOT

system_guidelines: |
    <i>Questions? Email your administrator (your@email.com)</i>
    <h3>General</h3>
    <p>Fix typos.</p>

roles:
  'user:user': 10
  'user:creator': 30
  'user:admin': 50
  'user:siteadmin': 100
  'project:proofer': 1000
  'project:reviewer': 2000
  'project:admin': 5000

private_key: 'hash together a private key and put it here'

devkeys:
  unbindery: 'hash together a dev key and put it here'

google_analytics: UA-YOUR-GA-CODE

scoring:
  proof: 5                              # how many points proofing an item is worth
  review: 5                             # how many points reviewing an item is worth

editors:
  page:
    css: # [custompage.css]             # array of CSS to include for this editor type
  audio:
    js: # [customaudio.js]              # ditto
# xml:
#   css: # [xml.css]                    # custom editor type

uploaders:
  Page:
    extensions: [ jpg, jpeg, png, gif ]
  Audio:
    extensions: [ mp3 ]
    ffmpeg: /usr/local/bin/ffmpeg
    chunksize: 60                       # sixty seconds
    chunkoverlap: 2                     # two seconds

notifications:
  user_new:
    targets: [ @admin ]
    subject: "New user: {{username}}"
    message: "A new user has joined: {{username}}"
  user_save_transcript_draft:
    targets: [ @user ]
    subject: "Saved draft: {{item}}"
    message: "You successfully saved a draft of your transcript for item {{item}}."
  user_save_transcript_completed:
    targets: [ @user ]
    subject: "Finished item: {{item}}"
    message: "You successfully finished your transcript for item {{item}}."
  user_save_transcript_reviewed:
    targets: [ @user ]
    subject: "Reviewed item: {{item}}"
    message: "You successfully reviewed the transcript for item {{item}}."
  admin_save_transcript_draft:
    targets: [ @projectadmin ]
    subject: "Transcript saved ({{item}} by {{username}})"
    message: "{{username}} saved draft of transcript for {{item}}."
  admin_save_transcript_completed:
    targets: [ @projectadmin ]
    subject: "Finished: {{item}} by {{username}}"
    message: "{{username}} finished transcript for {{item}}."
  admin_save_transcript_reviewed:
    targets: [ @projectadmin ]
    subject: "Reviewed: {{item}} by {{username}}"
    message: "{{username}} finished reviewing the transcript for {{item}}."
